// FILE: ipcChannels.ts
// Purpose: Defines the data-only IPC channel contract shared by Electron main and preload.
// Layer: Desktop IPC contract

export const DESKTOP_IPC_CHANNELS = {
  pickFolder: "desktop:pick-folder",
  saveFile: "desktop:save-file",
  confirm: "desktop:confirm",
  setTheme: "desktop:set-theme",
  setLocale: "desktop:set-locale",
  getLocale: "desktop:get-locale",
  getAppIcon: "desktop:get-app-icon",
  setAppIcon: "desktop:set-app-icon",
  contextMenu: "desktop:context-menu",
  openExternal: "desktop:open-external",
  safariAccess: {
    getInfo: "desktop:safari-access-info",
    openSettings: "desktop:safari-access-settings",
    revealApp: "desktop:safari-access-reveal-app",
  },
  showInFolder: "desktop:show-in-folder",
  clipboardWriteImage: "desktop:clipboard-write-image",
  windowMinimize: "desktop:window-minimize",
  windowToggleMaximize: "desktop:window-toggle-maximize",
  windowClose: "desktop:window-close",
  windowGetState: "desktop:window-get-state",
  windowState: "desktop:window-state",
  customTitleBarGetState: "desktop:custom-title-bar-get-state",
  customTitleBarSetPreference: "desktop:custom-title-bar-set-preference",
  customTitleBarRelaunch: "desktop:custom-title-bar-relaunch",
  menuAction: "desktop:menu-action",
  quitConfirmationRequest: "desktop:quit-confirmation-request",
  quitConfirmationResponse: "desktop:quit-confirmation-response",
  updateState: "desktop:update-state",
  updateGetState: "desktop:update-get-state",
  updateCheck: "desktop:update-check",
  updateDownload: "desktop:update-download",
  updateInstall: "desktop:update-install",
  notificationsIsSupported: "desktop:notifications-is-supported",
  notificationsShow: "desktop:notifications-show",
  zoomFactor: "desktop:zoom-factor",
  zoomFactorChanged: "desktop:zoom-factor-changed",
  wsUrl: "desktop:get-ws-url",
  transcribeVoice: "desktop:server-transcribe-voice",
  computerPreviewFrame: "computerPreview.frame",
  computerSetCursorStyle: "desktop:computer-set-cursor-style",
  storageMigration: {
    read: "desktop:storage-migration-read",
    acknowledge: "desktop:storage-migration-acknowledge",
  },
  appSnap: {
    captureCurrentApp: "desktop:appsnap-capture-current-app",
    cancelCapture: "desktop:appsnap-cancel-capture",
    getState: "desktop:appsnap-get-state",
    setEnabled: "desktop:appsnap-set-enabled",
    checkShortcut: "desktop:appsnap-check-shortcut",
    setShortcut: "desktop:appsnap-set-shortcut",
    requestPermissions: "desktop:appsnap-request-permissions",
    startPermissionSetup: "desktop:appsnap-start-permission-setup",
    listPendingCaptures: "desktop:appsnap-list-pending-captures",
    acknowledgeCapture: "desktop:appsnap-acknowledge-capture",
    listWindows: "desktop:appsnap-list-windows",
    captureWindow: "desktop:appsnap-capture-window",
    openPermissionSettings: "desktop:appsnap-open-permission-settings",
    restartApp: "desktop:appsnap-restart-app",
    showPermissionGuide: "desktop:appsnap-show-permission-guide",
    hidePermissionGuide: "desktop:appsnap-hide-permission-guide",
    permissionGuideState: "desktop:appsnap-permission-guide-state",
    captured: "desktop:appsnap-captured",
    error: "desktop:appsnap-error",
    state: "desktop:appsnap-state",
  },
  browser: {
    vault: {
      snapshot: "desktop:browser-vault-snapshot",
      configure: "desktop:browser-vault-configure",
      remove: "desktop:browser-vault-remove",
      respond: "desktop:browser-vault-respond",
      setupMaster: "desktop:browser-vault-setup-master",
      unlock: "desktop:browser-vault-unlock",
      lock: "desktop:browser-vault-lock",
      reveal: "desktop:browser-vault-reveal",
      cookieSources: "desktop:browser-cookie-sources",
      cookieProfiles: "desktop:browser-cookie-profiles",
      importCookies: "desktop:browser-cookie-import",
      changed: "desktop:browser-vault-changed",
    },
    webMcpCompatibilityPolicy: "desktop:browser-webmcp-compatibility-policy",
    state: "desktop:browser-state",
    open: "desktop:browser-open",
    close: "desktop:browser-close",
    hide: "desktop:browser-hide",
    getState: "desktop:browser-get-state",
    setBounds: "desktop:browser-set-bounds",
    attachWebview: "desktop:browser-attach-webview",
    detachWebview: "desktop:browser-detach-webview",
    requestOpenPanel: "desktop:browser-use-request-open-panel",
    copyLink: "desktop:browser-copy-link",
    requestCopyLink: "desktop:browser-request-copy-link",
    copyScreenshotToClipboard: "desktop:browser-copy-screenshot-to-clipboard",
    captureScreenshot: "desktop:browser-capture-screenshot",
    capturePreview: "desktop:browser-capture-preview",
    navigate: "desktop:browser-navigate",
    reload: "desktop:browser-reload",
    goBack: "desktop:browser-go-back",
    goForward: "desktop:browser-go-forward",
    newTab: "desktop:browser-new-tab",
    closeTab: "desktop:browser-close-tab",
    selectTab: "desktop:browser-select-tab",
    openDevTools: "desktop:browser-open-devtools",
    annotations: {
      start: "desktop:browser-annotations-start",
      cancel: "desktop:browser-annotations-cancel",
      syncMarkers: "desktop:browser-annotations-sync-markers",
      event: "desktop:browser-annotations-event",
      guestMessage: "desktop:browser-annotations-guest-message",
    },
  },
} as const;

export const BROWSER_IPC_CHANNELS = DESKTOP_IPC_CHANNELS.browser;
export const BROWSER_ANNOTATION_GUEST_COMMAND_CHANNEL = "desktop:browser-annotations-guest-command";
export const APPSNAP_IPC_CHANNELS = DESKTOP_IPC_CHANNELS.appSnap;
export const DESKTOP_WS_URL_CHANNEL = DESKTOP_IPC_CHANNELS.wsUrl;
export const SERVER_TRANSCRIBE_VOICE_CHANNEL = DESKTOP_IPC_CHANNELS.transcribeVoice;
